### ISSUE TITLE
Positions/ Wege Tracking

### ISSUE THREAD

**Issue by knutator2** [Datenschule/datenspaziergang-app#36]
- [ ] ~Pop Up zum Abfragen ob die Position verwendet werden kann~
- [x] Ständiges User Tracking um zu sehen
- [x] Anzeige der Route von einer Station zur nächsten

**Comment by lislis** [comment]
`mgl-control` übernimmt das geolocation-tracking für uns. Dann haben wir zwar kein Pop-up aber eine andere opt-in Methode.

**Comment by lislis** [comment]
Popup kommt von Android direkt.
Funktioniert super!
